# Generated by Django 2.2 on 2019-05-19 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medicine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_blood_pressure', models.PositiveIntegerField(verbose_name='min heart rate')),
                ('max_blood_pressure', models.PositiveIntegerField(verbose_name='max heart rate')),
                ('glucose_rate', models.FloatField(verbose_name='glucose rate')),
                ('protein_rate', models.FloatField(verbose_name='protein rate')),
                ('albumin_rate', models.FloatField(verbose_name='albumin rate')),
                ('myoglobin_rate', models.FloatField(verbose_name='myoglobin rate')),
                ('ferritin_rate', models.FloatField(verbose_name='ferritin rate')),
                ('cholesterol_rate', models.FloatField(verbose_name='cholesterol rate')),
                ('temperature', models.FloatField(verbose_name='temperature')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'statistics',
                'verbose_name_plural': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('description', models.TextField(verbose_name='description')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('time', models.TimeField(verbose_name='time')),
                ('days', medicine.models.PatchedMultiSelectField(choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thu', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday'), ('evr', 'everyday')], max_length=31, verbose_name='days')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('pending', models.BooleanField(default=True, verbose_name='pending')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Schedule', verbose_name='schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.TextField(verbose_name='verdict')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Statistics')),
            ],
            options={
                'verbose_name': 'diagnosis',
                'verbose_name_plural': 'diagnosis',
            },
        ),
    ]
