# Generated by Django 2.2 on 2019-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterField(
            model_name='statistics',
            name='max_blood_pressure',
            field=models.PositiveIntegerField(verbose_name='max pressure'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='min_blood_pressure',
            field=models.PositiveIntegerField(verbose_name='min pressure'),
        ),
    ]
