# Generated by Django 2.2 on 2019-05-21 19:54

from django.db import migrations
import medicine.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20190521_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='verdict',
            field=medicine.models.PatchedMultiSelectField(choices=[('high_blood_pressure', 'Hypertension causes symptoms such as headache, shortness of breath, dizziness, chest pain, heart palpitations and nosebleeds.'), ('low_blood_pressure', 'Low blood pressure can cause impaired blood supply in certain parts of the brain responsible for hearing and vision, which can cause deafness and reduced vision.'), ('high_glucose', 'Glucose elevation is observed when:diabetes, pancreatic tumors, stress and others.'), ('high_glucose', 'Low blood pressure can cause impaired blood supply in certain parts of the brain responsible for hearing and vision, which can cause deafness and reduced vision.'), ('high_protein', 'Increased protein content in the blood is observed with: intestinal obstruction, acute and chronic infectious diseases, etc.'), ('low_protein', 'The decrease in the protein content in the blood is observed when: pancreatitis, hepatitis, injuries, etc.'), ('high_albumin', 'An increase in the level of albumin is observed when dehydration of the body.'), ('low_albumin', 'The decrease in albumin level is observed when: malnutrition (insufficient intake of proteins from food), chronic liver diseases, etc.'), ('high_myoglobin', 'Increased myoglobin level is observed with:injuries, convulsions, burns. Physiological elevation of myoglobin often occurs during muscle overload.'), ('low_myoglobin', 'A decrease in myoglobin level is observed when: polymyositis.'), ('high_ferritin', 'An increase in the level of ferritin is observed when: acute hepatitis.'), ('low_ferritin', 'A decrease in the level of ferritin is observed in case of iron deficiency anemia.'), ('high_temperature', 'High temperature can cause bad feeling, weakness in limbs and whole body.'), ('high_temperature', 'High temperature can cause bad feeling, weakness in limbs and whole body.'), ('good_health', 'Health is in good condition.')], max_length=216, verbose_name='verdict'),
        ),
    ]
